on: 
  pull_request:
    branches: [ main ]
name: 🚀 Deploy website
jobs:
  Deploy:
    name: Deploy Laravel Backend
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist


    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server_dir: ${{ secrets.BACKEND_DIR }}
        protocal: ftps

        exclude:
          - **/.git*
          - **/.git*/**
          - **/node_modules/**
          - public
          - .env
          - storage
          - server
