on: 
  pull_request:
    branches: [ main ]
name: 🚀 Deploy website
jobs:
  Deploy-Frontend:
    name: React Frontend
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
   
    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run prod

  
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: /public/
        server-dir: ${{ secrets.FRONTEND_DIR }}
        protocol: ftps

    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}  
        slack-message: 'CarDrive Frontend Deployment Successful!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}    
