name: Deploy CarDrive Application

on: 
  pull_request:
    branches: [ main ]

jobs:
  Deploy-Frontend:
    name: Compile React Frontend & Css
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2   
    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'   

    - name: 🔨 Build Project
      run: |
        npm install
        npm run prod  

    - name: Upload Frontend
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: ./public/
        server-dir: ${{ secrets.FRONTEND_DIR }}
        protocol: ftps
        exclude: "[index.php]"

    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}  
        slack-message: 'CarDrive Frontend Deployed Successful!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   

  Deploy-Backend:
    name: Build Laravel Backend
    runs-on: ubuntu-latest

    steps:   
    - name: 🚚 Get latest code 
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  
              
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Upload Backend
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: ${{ secrets.BACKEND_DIR }}
        protocol: ftps
        exclude: "[**/public/**,.env,**/storage/**,server.php]"

    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}  
        slack-message: 'CarDrive Backend Deployed Successfully!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 
