on: 
  pull_request:
    branches: [ main ]
name: 🚀 Deploy website
jobs:
  Deploy:
    name: Deploy React Frontend
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
   
    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run prod

  
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local_dir: /public/
        server_dir: ${{ secrets.FRONTEND_DIR }}
        protocal: ftps
        
