- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.14.0
  with:
    channel-id: ${{ secrets.SLACK_BOT_TOKEN }}  
    slack-message: 'posting from a github action!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
